from . import crm_lead
from . import crm_lead_type
from . import crm_lead_modality
from . import crm_lead_scope
from . import crm_lead_channel
from . import crm_lead_structure_type
from . import crm_lead_structure_model
from . import crm_lead_revision
from . import crm_lead_fee
from . import crm_tension_level
from . import crm_lead_evacuation
from . import crm_lead_revision_prices
from . import crm_lead_revision_global_type
from . import crm_leadopportunity_partner
from . import crm_lead_revision_direct_costs
from . import crm_lead_revision_inverter
from . import crm_lead_revision_battery
from . import offer_class
from . import crm_lead_revision_energy_simulation_production
from . import crm_lead_revision_energy_simulation_demand
